run : 161044054_main.o LinkedList.o Iterator.o HashSet.o ArrayList.o
	g++ -o run  161044054_main.o LinkedList.o Iterator.o HashSet.o ArrayList.o

161044054_main.o : 161044054_main.cpp
	g++ -c 161044054_main.cpp -std=c++11

LinkedList.o : LinkedList.cpp
	g++ -c LinkedList.cpp -std=c++11

Iterator.o : Iterator.cpp
	g++ -c Iterator.cpp -std=c++11

HashSet.o : HashSet.cpp
	g++ -c HashSet.cpp -std=c++11

ArrayList.o : ArrayList.cpp
	g++ -c ArrayList.cpp -std=c++11
	
